### ISSUE TITLE
Broken link in readme

### ISSUE THREAD

**Issue by RayBB** [johanngan/pmd-bot#1]
Readme has a link "FCEUX Lua" 404's
https://tasvideos.github.io/fceux/web/help/fceux.html?LuaScripting.html

Perhaps it should link here? https://fceux.com/web/help/LuaScripting.html

**Comment by johanngan** [comment]
Oh yeah you're right, guess the link changed at some point.

Fixed with https://github.com/johanngan/pmd-bot/commit/8f068e73a676dfa3e0d74cb4626f0480f7bb5668. Thanks!
